
/** 
 * Model for the Report data generated by ReportManager
 * @prop timestamp Time stamp from report generation
 * @prop categoryData Collection of category specific data following {@link ReportCategory}
 * @author James Wilson
*/
export interface Report {
    timestamp: Date,
    totalClaims: number,
    totalPending: number,
    totalApproved: number,
    totalDenied:number,
    totalPendingExpense: number,
    totalApprovedExpense: number,
    totalPendingPercent: number,
    totalApprovedPercent: number,
    totalDeniedPercent:number,
    categoryData: ReportCategory[],
}

/** 
 * Model for category specific data used by {@link Report}
 * @prop name Category Name
 * @prop total Total number of claims in category
 * @prop categoryPercent Percentage of category in all categories
 * @author James Wilson
*/
export interface ReportCategory {
    name: string,
    total: number,
    categoryPercent: number,
    pending: number,
    approved: number,
    denied: number,
    pendingExpense: number,
    approvedExpense: number,
    pendingPercent: number,
    approvedPercent: number,
    deniedPercent: number,
}